apiVersion: v1
kind: Service
metadata:
  name: grpc-pingpong-service
spec:
  selector:
    app: grpc-pingpong
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 8080
      nodePort: 31110